-- procedure 1
CREATE PROCEDURE SP_INSERT_VOTE 
	@ID_CONT INT, 
	@ID_CANDIDAT INT, 
	@ID_PARTID INT,
	@ID_SCRUTIN INT
AS
BEGIN
	BEGIN TRAN;

	INSERT INTO VOTURI
	VALUES
	(@ID_CONT, @ID_SCRUTIN, @ID_CANDIDAT, @ID_PARTID)

	IF @@ERROR <> 0
		BEGIN
			ROLLBACK;
			PRINT 'Tranzactie esuata';
		END
	ELSE
		BEGIN
			COMMIT;
			PRINT 'Tranzactie completata cu succes';
		END
END;
GO

-- procedure 2
CREATE PROCEDURE SP_GET_VOTE @ID_CONT INT, @ID_SCRUTIN INT
AS
SELECT COUNT(*) FROM VOTURI
WHERE ID_CONT = @ID_CONT AND ID_SCRUTIN = @ID_SCRUTIN;
GO