-- procedure 1
CREATE PROCEDURE SP_GET_POLLS
AS
SELECT ID_SCRUTIN, DENUMIRE, DATA_INCEPUT, DATA_SFARSIT
FROM SCRUTINE
GO

-- procedure 1.1
CREATE PROCEDURE SP_GET_POLLS_DETAILS
AS
SELECT * FROM VW_POLLS_DETAILS
ORDER BY DATA_INCEPUT DESC;
GO

-- procedure 2
CREATE PROCEDURE SP_GET_POLL_PARTICIPANTS @POLL_ID INT
AS
BEGIN
	IF (SELECT DISTINCT TIP_SCRUTIN FROM SCRUTINE WHERE ID_SCRUTIN = @POLL_ID) = 1
		SELECT * FROM VW_SCRUTINE_CANDIDATI
		WHERE ID_SCRUTIN = @POLL_ID AND ID_CANDIDAT IS NOT NULL
	ELSE 
		SELECT * FROM VW_SCRUTINE_PARTIDE
		WHERE ID_SCRUTIN = @POLL_ID AND ID_PARTID IS NOT NULL
END
GO

-- procedure 3
CREATE PROCEDURE SP_GET_POLL_RESULTS @ID_SCRUTIN INT
AS
WITH CTE AS (
	SELECT * FROM VW_POLL_RESULTS_PER_INDIVIDUAL
	UNION
	SELECT * FROM VW_VIEW_POLL_RESULTS_PER_PARTY
)
SELECT DISTINCT ID_SCRUTIN, DENUMIRE, DATA_INCEPUT, ID_CANDIDAT, URL_POZA_CANDIDAT, NUME, PRENUME, TOTAL_VOTURI, VOTURI_CANDIDAT, PROCENTAJ_CANDIDAT FROM CTE
WHERE ID_SCRUTIN = @ID_SCRUTIN
ORDER BY VOTURI_CANDIDAT DESC, NUME, PRENUME;
GO

-- procedure 4
CREATE PROCEDURE SP_INSERT_POLL @NAME VARCHAR(255), @POLL_TYPE INT, @START_DATE DATETIME, @END_DATE DATETIME
AS
INSERT INTO SCRUTINE
VALUES
(@NAME, @POLL_TYPE, @START_DATE, @END_DATE);
GO

-- procedure 5
CREATE PROCEDURE SP_INSERT_POLL_PARTICIPANT @POLL_ID INT, @PARTICIPANT_ID INT, @PARTY_ID INT, @REGISTER_DATE DATETIME
AS
INSERT INTO SCRUTINE_CANDIDATI
VALUES
(@POLL_ID, @PARTICIPANT_ID, @PARTY_ID, @REGISTER_DATE);
GO

-- procedure 6
CREATE PROCEDURE SP_UPDATE_POLL @POLL_ID INT, @NAME VARCHAR(255), @START_DATE DATETIME, @END_DATE DATETIME
AS
UPDATE SCRUTINE
SET DENUMIRE = @NAME, DATA_INCEPUT = @START_DATE, DATA_SFARSIT = @END_DATE
WHERE ID_SCRUTIN = @POLL_ID;
GO

-- procedure 7
CREATE PROCEDURE SP_DELETE_POLL @POLL_ID INT
AS
DELETE FROM VOTURI
WHERE ID_SCRUTIN = @POLL_ID;
GO

-- procedure 8
CREATE PROCEDURE SP_DELETE_POLL_PARTICIPANT @POLL_ID INT, @PARTICIPANT_ID INT
AS
DELETE FROM SCRUTINE_CANDIDATI 
WHERE ID_SCRUTIN = @POLL_ID AND ID_CANDIDAT = @PARTICIPANT_ID;
GO