-- procedure 1
CREATE PROCEDURE SP_INSERT_NEW_PARTY
	@DENUMIRE VARCHAR(255),
	@ABREVIERE VARCHAR(10),
	@ID_STATUT INT,
	@URL_LOGO VARCHAR(1000)
AS
INSERT INTO PARTIDE (DENUMIRE, ABREVIERE, ID_STATUT, URL_LOGO_PARTID)
VALUES
(@DENUMIRE, @ABREVIERE, @ID_STATUT, @URL_LOGO);
GO

-- procedure 2
CREATE PROCEDURE SP_UPDATE_PARTY
	@ID_PARTID INT,
	@DENUMIRE VARCHAR(255),
	@ABREVIERE VARCHAR(10),
	@ID_STATUT INT,
	@URL_LOGO VARCHAR(1000)
AS
UPDATE PARTIDE
SET DENUMIRE = @DENUMIRE, ABREVIERE = @ABREVIERE, ID_STATUT = @ID_STATUT, URL_LOGO_PARTID = @URL_LOGO
WHERE ID_PARTID = @ID_PARTID;
GO