-- procedure 1
CREATE PROCEDURE SP_INSERT_NEW_PARTICIPANT 
	@IDNP CHAR(13), 
	@NUME VARCHAR(100), 
	@PRENUME VARCHAR(100),
	@PATRONIMIC VARCHAR(100),
	@URL_POZA VARCHAR(1000),
	@ID_PARTID INT
AS
INSERT INTO CANDIDATI
VALUES
(@IDNP, @NUME, @PRENUME, @PATRONIMIC, @URL_POZA, @ID_PARTID);
GO

-- procedure 2
CREATE PROCEDURE SP_UPDATE_PARTICIPANT 
	@ID_CANDIDAT INT,
	@IDNP CHAR(13), 
	@NUME VARCHAR(100), 
	@PRENUME VARCHAR(100),
	@PATRONIMIC VARCHAR(100),
	@URL_POZA VARCHAR(1000),
	@ID_PARTID INT
AS
	UPDATE CANDIDATI
	SET IDNP = @IDNP, NUME = @NUME, PRENUME = @PRENUME, PATRONIMIC = @PATRONIMIC,
	URL_POZA_CANDIDAT = @URL_POZA, ID_PARTID = @ID_PARTID
	WHERE ID_CANDIDAT = @ID_CANDIDAT;
GO