CREATE TABLE STATUTURI
(
	ID_STATUT INT PRIMARY KEY,
	STATUT VARCHAR(20) UNIQUE CHECK(STATUT IN ('Activ', 'Inactiv', 'Suspendat')) NOT NULL
);

CREATE TABLE ROLURI_UTILIZATOR
(
	ID_ROL INT PRIMARY KEY,
	ROL VARCHAR(20) UNIQUE CHECK(ROL IN ('Administrator', 'Utilizator')) NOT NULL
);

CREATE TABLE TIP_SCRUTIN
(
	ID_TIP INT PRIMARY KEY,
	TIP_SCRUTIN VARCHAR(20) UNIQUE CHECK(TIP_SCRUTIN IN ('Individual', 'Partid')) NOT NULL
);

CREATE TABLE LOCALITATI
(
	ID_LOCALITATE INT PRIMARY KEY IDENTITY(1, 1),
	DENUMIRE NVARCHAR(100) NOT NULL,
	RAION NVARCHAR(100) NOT NULL
);
-- DROP TABLE LOCALITATI

CREATE TABLE UTILIZATORI
(
	ID_UTILIZATOR INT PRIMARY KEY IDENTITY(1, 1),
	IDNP CHAR(13) UNIQUE CHECK(LEN(IDNP) = 13) NOT NULL,
	NUME VARCHAR(100) NOT NULL,
	PRENUME VARCHAR(100) NOT NULL,
	PATRONIMIC VARCHAR(100),
	DATA_NASTERII DATE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
	TELEFON VARCHAR(15) UNIQUE,
	ID_ROL INT NOT NULL,
	ID_STATUT INT NOT NULL,
	CONSTRAINT FK_ID_ROL FOREIGN KEY (ID_ROL) REFERENCES ROLURI_UTILIZATOR(ID_ROL) ON DELETE CASCADE,
	CONSTRAINT FK_ID_STATUT FOREIGN KEY (ID_STATUT) REFERENCES STATUTURI(ID_STATUT) ON DELETE CASCADE
);

CREATE TABLE DETALII_UTILIZATOR
(
	ID_DETALII INT PRIMARY KEY IDENTITY(1, 1),
	ID_UTILIZATOR INT UNIQUE NOT NULL,
	CONSTRAINT FK_ID_UTILIZATOR FOREIGN KEY(ID_UTILIZATOR) REFERENCES UTILIZATORI (ID_UTILIZATOR) ON DELETE CASCADE,
	SERIA_BULETIN CHAR(9) UNIQUE CHECK(LEN(SERIA_BULETIN) = 9) NOT NULL,
	DATA_EMITERII_BULETIN DATE NOT NULL,
	DATA_EXPIRARII_BULETIN DATE NOT NULL,
	ID_LOCALITATE INT NOT NULL,
	CONSTRAINT FK_ID_LOCALITATE FOREIGN KEY (ID_LOCALITATE) REFERENCES LOCALITATI(ID_LOCALITATE),
	ADRESA VARCHAR(100)
);


CREATE TABLE CONTURI
(
	CONT_ID INT PRIMARY KEY IDENTITY(1, 1),
	ID_UTILIZATOR INT UNIQUE NOT NULL,
	CONSTRAINT FK_CONT_ID_UTILIZATOR FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATORI(ID_UTILIZATOR),
	PAROLA VARCHAR(255) NOT NULL
);
-- DROP TABLE CONTURI

-- drop table partide
CREATE TABLE PARTIDE
(
	ID_PARTID INT PRIMARY KEY IDENTITY(1, 1),
	DENUMIRE NVARCHAR(255) UNIQUE NOT NULL,
	ABREVIERE NVARCHAR(10) UNIQUE,
	URL_LOGO_PARTID VARCHAR(MAX),
	ID_STATUT INT NOT NULL,
	CONSTRAINT FK_PARTID_ID_STATUT FOREIGN KEY (ID_STATUT) REFERENCES STATUTURI (ID_STATUT)
);

-- drop table candidati
CREATE TABLE CANDIDATI 
(
	ID_CANDIDAT INT PRIMARY KEY IDENTITY(1, 1),
	IDNP CHAR(13) UNIQUE CHECK(LEN(IDNP) = 13) NOT NULL,
	NUME VARCHAR(100) NOT NULL,
	PRENUME VARCHAR(100) NOT NULL,
	PATRONIMIC VARCHAR(100),
	URL_POZA_CANDIDAT VARCHAR(1000),
	ID_PARTID INT,
	CONSTRAINT FK_ID_CANDIDAT_PARTID FOREIGN KEY (ID_PARTID) REFERENCES PARTIDE(ID_PARTID)
);

-- drop table scrutine
CREATE TABLE SCRUTINE
(
	ID_SCRUTIN INT PRIMARY KEY IDENTITY(1, 1),
	DENUMIRE VARCHAR(255) UNIQUE NOT NULL,
	TIP_SCRUTIN INT NOT NULL,
	DATA_INCEPUT DATETIME NOT NULL,
	DATA_SFARSIT DATETIME NOT NULL,
	CONSTRAINT FK_TIP_SCRUTIN FOREIGN KEY (TIP_SCRUTIN) REFERENCES TIP_SCRUTIN(ID_TIP)
);

-- drop table scrutine_candidati
CREATE TABLE SCRUTINE_CANDIDATI
(
	ID_SCRUTIN INT NOT NULL,
	ID_CANDIDAT INT,
	ID_PARTID INT,
	DATA_ORA_INREGISTRARII DATETIME NOT NULL,
	CONSTRAINT FK_ID_SCRUTIN FOREIGN KEY (ID_SCRUTIN) REFERENCES SCRUTINE(ID_SCRUTIN),
	CONSTRAINT FK_ID_CANDIDAT FOREIGN KEY (ID_CANDIDAT) REFERENCES CANDIDATI(ID_CANDIDAT),
	CONSTRAINT FK_ID_PARTID_SCRUTIN FOREIGN KEY (ID_PARTID) REFERENCES PARTIDE(ID_PARTID),
	CONSTRAINT UQ_RECORD UNIQUE (ID_SCRUTIN, ID_CANDIDAT, ID_PARTID)
);

-- drop table voturi
CREATE TABLE VOTURI 
(
	ID_CONT INT NOT NULL,
	ID_SCRUTIN INT NOT NULL,
	PRIMARY KEY (ID_CONT, ID_SCRUTIN),
	ID_CANDIDAT INT,
	ID_PARTID INT,
	CONSTRAINT FK_ID_VOT_CONT FOREIGN KEY (ID_CONT) REFERENCES CONTURI (CONT_ID),
	CONSTRAINT FK_ID_VOT_SCRUTIN FOREIGN KEY (ID_SCRUTIN) REFERENCES SCRUTINE (ID_SCRUTIN)
);

CREATE TABLE DESCRIERE_NOTIFICARI (
	ID_DESCRIERE INT PRIMARY KEY IDENTITY(1, 1),
	TITLU VARCHAR(255) NOT NULL,
	DESCRIERE VARCHAR(1000) UNIQUE NOT NULL
);

CREATE TABLE NOTIFICARI (
	ID_NOTIFICARE INT PRIMARY KEY IDENTITY(1, 1),
	ID_UTILIZATOR INT FOREIGN KEY REFERENCES UTILIZATORI(ID_UTILIZATOR),
	ID_DESCRIERE INT FOREIGN KEY REFERENCES DESCRIERE_NOTIFICARI(ID_DESCRIERE),
	VALOAREA_VECHE VARCHAR(255),
	VALOAREA_NOUA VARCHAR(255),
	NOTIFICARE_CITITA CHAR(1) CHECK(NOTIFICARE_CITITA IN ('Y', 'N')) DEFAULT 'N',
	DATA_NOTIFICARE DATETIME NOT NULL
);