-- function 1
CREATE FUNCTION GetPollCountUser(@POLL_ID INT)
RETURNS INT
AS
BEGIN
	RETURN (
		SELECT COUNT(DISTINCT ID_CONT) AS C 
		FROM VOTURI 
		WHERE ID_SCRUTIN = @POLL_ID
	)
END;
GO

-- function 2
CREATE FUNCTION GetCountUnreadNotifications(@USER_ID INT)
RETURNS INT
AS 
BEGIN
	RETURN (
		SELECT COUNT(ID_NOTIFICARE) AS C
		FROM NOTIFICARI
		WHERE ID_UTILIZATOR = @USER_ID AND NOTIFICARE_CITITA = 'N'
	)
END;
GO